In [1]:
import os


In [2]:
print(os.listdir())

In [3]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
%matplotlib inline

In [5]:
data = pd.read_csv('./Social_Network_Ads.csv')

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [7]:
data.head(5)

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [8]:
#split data
X = data.iloc[:,[2,3]].values

In [9]:
y = data.iloc[:,4].values

In [10]:
#splitting of data into train and test dataset
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25)

In [12]:
y_test

array([0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

In [13]:
X_test

array([[    19,  25000],
       [    48,  96000],
       [    30, 107000],
       [    38,  50000],
       [    35,  91000],
       [    31,  71000],
       [    59,  29000],
       [    27,  17000],
       [    39,  42000],
       [    35,  39000],
       [    42, 149000],
       [    29,  43000],
       [    29, 148000],
       [    26,  30000],
       [    19,  19000],
       [    48,  33000],
       [    22,  63000],
       [    52, 150000],
       [    40,  75000],
       [    19,  76000],
       [    43, 133000],
       [    33, 149000],
       [    31,  74000],
       [    54, 104000],
       [    30, 135000],
       [    35,  55000],
       [    20,  82000],
       [    29,  28000],
       [    29,  43000],
       [    49,  65000],
       [    39,  59000],
       [    32, 150000],
       [    54,  26000],
       [    40,  78000],
       [    43, 129000],
       [    48, 119000],
       [    57,  26000],
       [    55,  39000],
       [    45,  32000],
       [    35, 147000],


In [14]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
# fit your training data to nb
from sklearn.naive_bayes import GaussianNB


In [16]:
classifier = GaussianNB()
classifier.fit(X_train,y_train)

GaussianNB()

In [17]:
#predict
y_predictor = classifier.predict(X_test)

In [18]:
y_predictor

array([0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

In [19]:
#detect things using confusion matrix
from sklearn.metrics import confusion_matrix
falseCalci = confusion_matrix(y_test,y_predictor)

In [20]:
falseCalci

array([[54,  6],
       [ 5, 35]], dtype=int64)