In [1]:
import os
print(os.listdir())

['.ipynb_checkpoints', 'Social_Network_Ads.csv', 'svm.ipynb']


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [3]:
%matplotlib inline


In [4]:
data = pd.read_csv('./Social_Network_Ads.csv')

In [5]:
#check info about data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [6]:
data.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [7]:
#split our dataset
X = data.iloc[:,[2,3]].values

In [8]:
y = data.iloc[:,[4]].values

In [9]:
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [10]:
#split into training and test dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [11]:
X_test

array([[    34, 115000],
       [    36, 118000],
       [    49,  88000],
       [    37, 146000],
       [    42, 104000],
       [    50,  20000],
       [    40,  57000],
       [    46,  28000],
       [    51, 146000],
       [    46,  32000],
       [    24,  55000],
       [    48, 138000],
       [    39, 134000],
       [    19,  19000],
       [    28, 123000],
       [    52, 114000],
       [    35,  77000],
       [    57, 122000],
       [    24,  89000],
       [    38, 113000],
       [    48,  35000],
       [    27,  31000],
       [    33,  60000],
       [    25,  22000],
       [    35,  61000],
       [    37, 144000],
       [    37,  72000],
       [    37,  78000],
       [    46,  88000],
       [    24,  19000],
       [    37,  74000],
       [    54,  70000],
       [    24,  23000],
       [    33,  28000],
       [    26,  15000],
       [    38,  50000],
       [    18,  52000],
       [    21,  72000],
       [    45,  22000],
       [    46,  79000],


In [12]:
#feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [13]:
X_train = sc.fit_transform(X_train)

In [14]:
X_test = sc.transform(X_test)

In [15]:
X_test

array([[-0.32574239,  1.36423664],
       [-0.13500577,  1.45348751],
       [ 1.1047823 ,  0.56097887],
       [-0.03963746,  2.28649557],
       [ 0.43720411,  1.03698348],
       [ 1.20015061, -1.46204072],
       [ 0.24646748, -0.36128006],
       [ 0.81867736, -1.22403841],
       [ 1.29551892,  2.28649557],
       [ 0.81867736, -1.10503726],
       [-1.27942552, -0.42078064],
       [ 1.00941399,  2.04849327],
       [ 0.15109917,  1.92949212],
       [-1.75626709, -1.491791  ],
       [-0.89795227,  1.60223895],
       [ 1.39088724,  1.33448636],
       [-0.23037408,  0.2337257 ],
       [ 1.8677288 ,  1.57248866],
       [-1.27942552,  0.59072916],
       [ 0.05573086,  1.30473607],
       [ 1.00941399, -1.0157864 ],
       [-0.99332058, -1.13478755],
       [-0.42111071, -0.2720292 ],
       [-1.18405721, -1.40254014],
       [-0.23037408, -0.24227891],
       [-0.03963746,  2.226995  ],
       [-0.03963746,  0.08497426],
       [-0.03963746,  0.26347599],
       [ 0.81867736,

In [16]:
#implement SVM
from sklearn.svm import SVC

In [17]:
classifier = SVC(kernel='linear')
classifier.fit(X_train, y_train.ravel())

SVC(kernel='linear')

In [18]:
#just predict
y_predictor = classifier.predict(X_test)

In [19]:
y_predictor

array([0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1], dtype=int64)

In [20]:
#consusuin matrix
from sklearn.metrics import confusion_matrix
errors = confusion_matrix(y_test, y_predictor)

In [21]:
errors

array([[42,  2],
       [12, 24]], dtype=int64)